In [2]:
import numpy as np

In [185]:
m1 = np.array(np.arange(1,11))
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [186]:
m1.shape

(10,)

In [187]:
m1.ndim

1

In [188]:
m1[[2,3,4,5]]

array([3, 4, 5, 6])

In [189]:
m2=m1.reshape(5,2)
m2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [199]:
a=m2[(m2%2==0) | (m2%3==0)].flatten()
j=a.shape
print(j[0]**2)

49


In [1]:
arr = [[1,21,6],[4,151,3],[7,81,9]]

In [2]:
arr

[[1, 21, 6], [4, 151, 3], [7, 81, 9]]

In [12]:
m3 = np.array(arr)
m3

array([[  1,  21,   6],
       [  4, 151,   3],
       [  7,  81,   9]])

In [20]:
m3[:,1].argsort()

array([0, 2, 1], dtype=int64)

In [22]:
m3[m3[:,1].argsort()]

array([[  1,  21,   6],
       [  7,  81,   9],
       [  4, 151,   3]])

In [25]:
m3[[1,0,2],:]

array([[  4, 151,   3],
       [  1,  21,   6],
       [  7,  81,   9]])

In [168]:
print(5 + (10-1)*3)
##nth term of AP - a +(n-1)d
np.linspace(5,32,10).astype('int32')


32


array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [309]:
m4 = np.array(np.arange(1,17)).reshape(16,1)
m4.shape
m4

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

#### 90 degree rotation of matrix
    2,0 1,0 0,0 
    2,1 1,1 0,1
    2,2 1,2 0,2
    
    7, 4, 1
    8, 5, 2
    9, 6, 3

In [312]:
l,m=m4.shape
m5 = np.ones((m,l)).astype('int32')
m5.shape

(1, 16)

In [313]:
for i in range(m4.shape[0]):
    for j in range(m4.shape[1]):
        m5[j,m5.shape[1]-1-i] = m4[i,j]
m5

array([[16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1]])

In [180]:
m3*m4

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [204]:
np.ceil(3.4287,2)

TypeError: return arrays must be of ArrayType

In [205]:
round(3.428,2)

3.43

In [249]:
np.exp(2)

7.38905609893065

In [250]:
arr = np.array([-2, -1, 0, 1, 2])
## [0.12 0.27 0.5 0.73 0.88] sigmod 1+e^(-arr[])

In [260]:
ans = 1/(1+np.exp(-arr))
np.around(ans,2)

array([0.12, 0.27, 0.5 , 0.73, 0.88])

In [262]:
X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [266]:
X.max(axis=1)

array([ 3,  7, 11])

In [267]:
X.sum()

66

In [268]:
X.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [271]:
[i.min() for i in X.T]

[0, 1, 2, 3]

In [4]:
row = np.array([0,1,2])
row[:,np.newaxis]

array([[0],
       [1],
       [2]])

In [14]:
arr = np.array([[1,2,3],[4,5,6]])
arr.shape
arr[:,np.newaxis]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [15]:
import numpy as np
X = np.arange(12).reshape((3, 4))
row = np.array([0, 1, 2])
mask = np.array([1, 0, 1, 0], dtype=bool)
print(X[row[:, np.newaxis], mask])

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [20]:
print(np.arange(0,2,0.5))
arr = 2*np.arange(0,2,0.5)
arr


[0.  0.5 1.  1.5]


array([0., 1., 2., 3.])

In [50]:
m1 = np.arange(16).reshape(1,16)
m1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [57]:
np.expand_dims(m1, axis=2)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15]]])

In [101]:
arr = np.array([1,2,3,4])
print(arr.shape)
print(np.max(arr),arr.shape[0])
l,m = arr.shape[0],np.max(arr)+1
print(l,m)
result = np.zeros((l,m),dtype='int')
print(result)
result[np.arange(l),arr] = 1
result

(4,)
4 4
4 5
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [145]:
#arr = np.array([-1,2,3,-4,5,6])
arr = np.array([-2,-3,3,4,5])
a=np.argwhere(arr>1)[0]
print(a)

[2]


In [138]:
print([np.where(arr>3)[0][0]])

[4]


In [194]:
2**0*1 + 2**1*1
arr=2**np.arange(12)
arr
bit = []

## Recursive Method to Convert Decimal to Binary

In [195]:
def deci_to_bin(deci):
    if deci == 0:
        return 0
          
    return 10*(deci_to_bin(deci//2))+(deci%2)

In [196]:
deci_to_bin(10)

1010

In [198]:
vectorize_deci_to_bin = np.vectorize(deci_to_bin)

In [199]:
vectorize_deci_to_bin(np.array([1,2,3]))

array([ 1, 10, 11])

In [5]:
top_left, top_right, bottom_left, bottom_right = (0,2), (5,7), (1,3), (6,9)
top_left_m = np.around(np.linspace(top_left[0],top_left[1],4),1).reshape(2,2)
top_right_m = np.around(np.linspace(top_right[0],top_right[1],4),1).reshape(2,2)
bottom_left_m = np.around(np.linspace(bottom_left[0],bottom_left[1],4),1).reshape(2,2)
bottom_right_m = np.around(np.linspace(bottom_right[0],bottom_right[1],4),1).reshape(2,2)
top_left_m, top_right_m, bottom_left_m, bottom_right_m

(array([[0. , 0.7],
        [1.3, 2. ]]),
 array([[5. , 5.7],
        [6.3, 7. ]]),
 array([[1. , 1.7],
        [2.3, 3. ]]),
 array([[6., 7.],
        [8., 9.]]))

In [12]:
ans = np.concatenate((np.concatenate((top_left_m,top_right_m), axis=1),np.concatenate((bottom_left_m,bottom_right_m), axis=1)),axis=0)
ans

array([[0. , 0.7, 5. , 5.7],
       [1.3, 2. , 6.3, 7. ],
       [1. , 1.7, 6. , 7. ],
       [2.3, 3. , 8. , 9. ]])

In [14]:
a = np.array([ [0, 6, 7, 9, 1], [2, 4, 6, 2, 7] ])
a.s

array([[0, 6, 7, 9, 1],
       [2, 4, 6, 2, 7]])

In [18]:
 np.tile(a,3).reshape(-1,5)

array([[0, 6, 7, 9, 1],
       [0, 6, 7, 9, 1],
       [0, 6, 7, 9, 1],
       [2, 4, 6, 2, 7],
       [2, 4, 6, 2, 7],
       [2, 4, 6, 2, 7]])

In [22]:
a = np.zeros(27).reshape(3, 3, 3)
b = np.arange(9).reshape(3, 3) 
a+b

array([[[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]],

       [[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]],

       [[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]])

In [23]:
a + b[np.newaxis, :, :]

array([[[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]],

       [[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]],

       [[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]])

In [46]:
mat=np.array([[1,2],[3,4],[5,6]])
l,m = mat.shape
ans = np.hstack((np.zeros([l+2,1],),np.vstack((np.zeros([1,m]),mat,np.zeros([1,m]))),np.zeros([l+2,1])))
ans2 = np.hstack((np.zeros([l+2,1],dtype='int'),np.vstack((np.zeros([1,m],dtype='int'),mat,np.zeros([1,m],dtype='int'))),np.zeros([l+2,1],dtype='int')))
print(ans.astype("int"),ans)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 5 6 0]
 [0 0 0 0]] [[0. 0. 0. 0.]
 [0. 1. 2. 0.]
 [0. 3. 4. 0.]
 [0. 5. 6. 0.]
 [0. 0. 0. 0.]]


In [42]:
np.zeros([1,2],dtype='int')

array([[0, 0]])