In [4]:
import numpy as np

In [185]:
m1 = np.array(np.arange(1,11))
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [186]:
m1.shape

(10,)

In [187]:
m1.ndim

1

In [188]:
m1[[2,3,4,5]]

array([3, 4, 5, 6])

In [189]:
m2=m1.reshape(5,2)
m2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [199]:
a=m2[(m2%2==0) | (m2%3==0)].flatten()
j=a.shape
print(j[0]**2)

49


In [1]:
arr = [[1,21,6],[4,151,3],[7,81,9]]

In [2]:
arr

[[1, 21, 6], [4, 151, 3], [7, 81, 9]]

In [12]:
m3 = np.array(arr)
m3

array([[  1,  21,   6],
       [  4, 151,   3],
       [  7,  81,   9]])

In [20]:
m3[:,1].argsort()

array([0, 2, 1], dtype=int64)

In [22]:
m3[m3[:,1].argsort()]

array([[  1,  21,   6],
       [  7,  81,   9],
       [  4, 151,   3]])

In [25]:
m3[[1,0,2],:]

array([[  4, 151,   3],
       [  1,  21,   6],
       [  7,  81,   9]])

In [168]:
print(5 + (10-1)*3)
##nth term of AP - a +(n-1)d
np.linspace(5,32,10).astype('int32')


32


array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [309]:
m4 = np.array(np.arange(1,17)).reshape(16,1)
m4.shape
m4

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

#### 90 degree rotation of matrix
    2,0 1,0 0,0 
    2,1 1,1 0,1
    2,2 1,2 0,2
    
    7, 4, 1
    8, 5, 2
    9, 6, 3

In [312]:
l,m=m4.shape
m5 = np.ones((m,l)).astype('int32')
m5.shape

(1, 16)

In [313]:
for i in range(m4.shape[0]):
    for j in range(m4.shape[1]):
        m5[j,m5.shape[1]-1-i] = m4[i,j]
m5

array([[16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1]])

In [180]:
m3*m4

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [204]:
np.ceil(3.4287,2)

TypeError: return arrays must be of ArrayType

In [205]:
round(3.428,2)

3.43

In [249]:
np.exp(2)

7.38905609893065

In [250]:
arr = np.array([-2, -1, 0, 1, 2])
## [0.12 0.27 0.5 0.73 0.88] sigmod 1+e^(-arr[])

In [260]:
ans = 1/(1+np.exp(-arr))
np.around(ans,2)

array([0.12, 0.27, 0.5 , 0.73, 0.88])

In [262]:
X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [266]:
X.max(axis=1)

array([ 3,  7, 11])

In [267]:
X.sum()

66

In [268]:
X.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [271]:
[i.min() for i in X.T]

[0, 1, 2, 3]